###

GET http://localhost:4000/api/usuarios

###

POST http://localhost:4000/api/usuarios
Content-Type: application/json

{
    "nombres": "El chamo",
    "apellidos": "es maraco",
    "tipoIdentificacion": "asd",
    "identificacion": "sad",
    "rol": "Administrador",
    "celular": "gsdfds",
    "residencia": "asdasda",
    "correo": "sadasddf",
    "contrasena": "gdfdffd",
    "fechaNacimiento": "ghgfgfgf",
    "estado": "hghjgjfg",
    "foto": "https://cdn.pixabay.com/photo/2020/10/11/03/16/silhouette-5644656__340.jpg"
  
}

###

GET http://localhost:4000/api/usuarios/63384a0f501e890d8090093e

###
DELETE http://localhost:4000/api/usuarios/63384a0f501e890d8090093e


###
PUT http://localhost:4000/api/usuarios/63386c9741d868b5723f01f3
Content-Type: application/json

{
    "rol": "Administrador"    
}

###

POST http://localhost:4000/api/usuarios/signup
Content-Type: application/json

{
    "nombres": "El chamo",
    "apellidos": "es maraco",
    "tipoIdentificacion": "asd",
    "identificacion": "sad",
    "rol": "Administrador",
    "celular": "gsdfds",
    "residencia": "asdasda",
    "correo": "sadasddf",
    "contrasena": "gdfdffd",
    "fechaNacimiento": "ghgfgfgf",
    "estado": "hghjgjfg",
    "foto": "https://cdn.pixabay.com/photo/2020/10/11/03/16/silhouette-5644656__340.jpg"

}

###

POST http://localhost:4000/api/usuarios/signin
Content-Type: application/json

{
    "correo": "sadasddf",
    "contrasena": "gdfdffd"
}


###

GET http://localhost:4000/api/productos

###

POST http://localhost:4000/api/productos
Content-Type: application/json

{
    "nombreProducto": "Chamo",
    "detalleProducto": "Chamo",
    "calificacion": "Chamo",
    "idUsuarioPoseedor": "Chamo",
    "descripcion": "Chamo",
    "precioAlquiler": "Chamo",
    "tiempoAlquiler": "Chamo",
    "marca": "Chamo",
    "modelo": "Chamo",
    "foto": "Chamo",
    "estado": "Chamo",
    "idUsuarioAlquilador": "Chamo"
}

###

GET http://localhost:4000/api/productos/633cd318f3febc8939002054

###
DELETE http://localhost:4000/api/productos/633cd2e9f3febc8939002052


###
PUT http://localhost:4000/api/productos/633cd318f3febc8939002054
Content-Type: application/json

{
    "nombreProducto": "Administrador"    
}

###

GET http://localhost:4000/api/servicios

###

###

POST http://localhost:4000/api/servicios
Content-Type: application/json

{
    "nombreServicio": "Chamo",
    "detalleServicio": "Chamo",
    "calificacion": "Chamo",
    "idUsuarioPoseedor": "Chamo",
    "descripcion": "Chamo",
    "precioAlquiler": "Chamo",
    "tiempoAlquiler": "Chamo",
    "marca": "Chamo",
    "modelo": "Chamo",
    "foto": "Chamo",
    "estado": "Chamo",
    "idUsuarioAlquilador": "Chamo"
}

###

GET http://localhost:4000/api/servicios/633cd318f3febc8939002054

###
DELETE http://localhost:4000/api/servicios/633cd2e9f3febc8939002052


###
PUT http://localhost:4000/api/servicios/633cd318f3febc8939002054
Content-Type: application/json

{
    "nombreServicio": "Administrador"    
}

