version: "3"

services:
  web:
    container_name: alquibackend
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  database:
    container_name: mibdmongo
    image: mongo
    ports:
      - "27018:27017"